apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hvegav
  description: Hugo account
spec:
  profile:
    displayName: Hugo Vega
    email: john@example.com
  memberOf:
    - admins  # If you want to associate the user with a group or team
  auth:
    github: hvegav  # The GitHub username associated with this user